spring:
  # MySQL connection properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost:3307/c4c}?createDatabaseIfNotExist=true&useSSL=false
  # Log JPA queries
  # Comment this in production
  jpa:
    show-sql: true
    # Drop and create new tables (create, create-drop, validate, update)
    # Only for testing purpose - comment this in production
    hibernate:
      ddl-auto: create-drop
    # Hibernate SQL dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: ${PORT:8080}