INSERT INTO links (link_namespace, link_short_code, link_redirect_url, link_created, link_expiry, link_owner) VALUES ('special:Home Page', 'home_page', 'https://computingforcompassion.org', current_timestamp(), null, null);
INSERT INTO links (link_namespace, link_short_code, link_redirect_url, link_created, link_expiry, link_owner) VALUES ('special:Invalid Link Redirect', 'invalid_link', 'https://computingforcompassion.org/events', current_timestamp(), null, null);

INSERT INTO links (link_namespace, link_short_code, link_redirect_url, link_created, link_expiry, link_owner) VALUES ('reserved_namespaces:Administration', 'admin', null, current_timestamp(), null, null);
INSERT INTO links (link_namespace, link_short_code, link_redirect_url, link_created, link_expiry, link_owner) VALUES ('reserved_namespaces:Administration', 'link', null, current_timestamp(), null, null);
INSERT INTO links (link_namespace, link_short_code, link_redirect_url, link_created, link_expiry, link_owner) VALUES ('reserved_namespaces:Administration', 'links', null, current_timestamp(), null, null);
INSERT INTO links (link_namespace, link_short_code, link_redirect_url, link_created, link_expiry, link_owner) VALUES ('reserved_namespaces:Administration', 'user', null, current_timestamp(), null, null);
INSERT INTO links (link_namespace, link_short_code, link_redirect_url, link_created, link_expiry, link_owner) VALUES ('reserved_namespaces:Administration', 'users', null, current_timestamp(), null, null);
INSERT INTO links (link_namespace, link_short_code, link_redirect_url, link_created, link_expiry, link_owner) VALUES ('reserved_namespaces:Resume Database', 'resume', null, current_timestamp(), null, null);
INSERT INTO links (link_namespace, link_short_code, link_redirect_url, link_created, link_expiry, link_owner) VALUES ('reserved_namespaces:Resume Database', 'resumes', null, current_timestamp(), null, null);
--INSERT INTO links (link_namespace, link_short_code, link_redirect_url, link_created, link_expiry, link_owner) VALUES ('reserved_globals:Resume Database', 'resumes', null, current_timestamp(), null, null);
INSERT INTO links (link_namespace, link_short_code, link_redirect_url, link_created, link_expiry, link_owner) VALUES ('reserved_globals:Resume Database', 'links', null, current_timestamp(), null, null);
INSERT INTO links (link_namespace, link_short_code, link_redirect_url, link_created, link_expiry, link_owner) VALUES ('reserved_globals:Resume Database', 'users', null, current_timestamp(), null, null);